### ISSUE TITLE
Is there a delay or any issues with total  downloads?

### ISSUE THREAD

**Issue by AlphaDaniel** [bogdanRada/ruby-gem-downloads-badge#1]
My downloads haven't changed since yesterday on badge but when i go to direct url it displays correctly seems like it only updates when I remove push and add back. I love the fact  that it shows the actual number and not rounding like Shields  ![Gem](https://img.shields.io/gem/dt/ruby_doc.svg)
 but doesn't seem to this point that it updates on its own. Can you maybe shed some light 

---
[![Downloads](http://ruby-gem-downloads-badge.herokuapp.com/ruby_doc?type=total&color=brightgreen)](https://rubygems.org/gems/ruby_doc)
at the time of writing this, using your markdown this displays `1508`

---
[Direct Link](http://ruby-gem-downloads-badge.herokuapp.com/ruby_doc?type=total&color=brightgreen)
and the direct link is showing the actual number `1613`

looking forward to hearing back

**Comment by bogdanRada** [comment]
hmm...i will investigate and will let you know what i find out. Seems something related to caching. Thanks for reporting this. Will try to find a solution as soon as i can.  I just deployed a few seconds ago  a new release of the application that uses ruby 2.5.0 and also the latest versions of gems.  Let me know if this still happpens .

**Comment by bogdanRada** [comment]
Hello. I did some testing and seems that GitHub changed something in their caching strategy. Tested with a different instance of the application deployed on another server and with badges on a different markdown file. Seems though that this is happening also when  the badge is in the description or comment on a issue or pull request.
Need more time to see what exactly had changed.
I come to this conclusion because I was looking at the logs while doing a few tens of requests and once the request is cached the others seem to not hit the application at all. I will try to find a solution as soon as possible.

**Comment by AlphaDaniel** [comment]
Awesome, sorry for the late reply just seen this and sounds good

**Comment by bogdanRada** [comment]
I think I found the solution.. I didn't had time to release it and didn't committed it yet to make sure that will work before I commit it to the repo.. So I will.need to test it a bit.and probably tomorrow or early next week will release the new version. Sorry for this but I have some personal things that need also some attention. Will try to release it as soon as possible.

**Comment by AlphaDaniel** [comment]
No worries, thanks so much

**Comment by bogdanRada** [comment]
Hello, I just released a new version. I think the problem was the Expires header. The helper changed in sinatra 2.0 and was overiding the cache control max age . It should work now. Please do let me know if there are still problems.

**Comment by AlphaDaniel** [comment]
Awesome will do and thanks :)
